name: Verify Pull Request
on: 
  pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/cache@v2
        with:
          path: TbD/TowerNinja/Library
          key: Library-TowerNinja-WebGL
          restore-keys: |
            Library-TowerNinja-
            Library-
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: ${{github.workspace}}/TowerNinja
          targetPlatform: WebGL
  