name: Publish game
on: 
  push:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: build
          lfs: true
      - name: merge to build
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: master
          target_branch: build
          github_token: ${{ github.token }}
      - name: cache
        uses: actions/cache@v2
        with:
          path: TbD/Library
          key: Library-TowerNinja-WebGL
          restore-keys: |
            Library-TowerNinja-
            Library-
      - name: build
        uses: game-ci/unity-builder@v2
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          projectPath: ${{github.workspace}}/TowerNinja
          targetPlatform: WebGL
